POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "John",
  "email": "johndoe@example.com",
  "description": "teste"
}

################

POST http://localhost:3000/api/countries
Content-Type: application/json

{
  "name": "Brasil"
}
################

POST http://localhost:3000/api/states
Content-Type: application/json

{
  "name": "Santa Catarina",
  "country_id": 1
}

################

POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Fantasy"
}

################

POST http://localhost:3000/api/books
Content-Type: application/json
Date: {{$datetime rfc1123}}


{
  "title": "Livro3",
  "date_publication": "{{$datetime '2021-02-12'}}",
  "price": "50",
  "isbn": "test-isbn",
  "brief": "resumo",
  "summary": "resumo",
  "pages": "200",
  "user_id": 4,
  "category_id": 1
}

################
GET http://localhost:3000/api/books

################
GET http://localhost:3000/api/countries

################

GET http://localhost:3000/api/books/1

################

POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "discount_id": 1,
  "book_id": 1,
  "itens": [
    {
      "idBook": 1,
      "quantity": 2
    },
    {
      "idBook": 2,
      "quantity": 2
    }
  ],
  "name": "teste",
  "middleName": "name",
  "email": "elvinciqueira@gmail.com",
  "cpf_cnpj": "11111111111",
  "country_id": 1,
  "cellphone": "11111111",
  "state": "São Paulo",
  "address": "Estrada de baixo",
  "city": "Diadema",
  "complement": "Eucaliptos",
  "cep": "09980400"
}

################

GET http://localhost:3000/api/orders/3
Content-Type: application/json

################

POST http://localhost:3000/api/order/discount
Content-Type: application/json
Date: {{$datetime rfc1123}}


{
  "code": "code-123",
  "percentage": 20,
  "expiration": "{{$datetime '2021-02-12'}}"
}